modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="https://github.com/KingRealzYT/Terraria-Reloaded/issues" #optional

[[mods]] #mandatory

modId="terrariareloaded" #mandatory

version="Alpha 1.0.0 (DevBuild - 10010112102020)" #mandatory

# How To Number This DevBuild - 100 <- This Is Mod Version + Time + Date
# Remove DevBuild Field For A Release
# Leave It For NOT Stable Alphas And Betas

displayName="Terraria Reloaded" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="https://www.curseforge.com/minecraft/mc-mods/terraria-reloaded" #optional

logoFile="examplemod.png" #optional

credits="Realz, Cookie, ISpartannnn, goldrat1, HamburgerBoi, PutoPug, models by goldrat1 and Xener_D" #optional

authors="KingRealzYT, _Cookie_, goldrat1, ISpartannnn, HamburgerBoi, PutoPug" #optional

description='''
This is Terraria Reloaded. It adds in stuff from the game Terraria into Minecraft!
'''

[[dependencies.terrariareloaded]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[31,)" #mandatory

    ordering="NONE"

    side="BOTH"

[[dependencies.terrariareloaded]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
